Drop SysV support

diff --git a/install b/install
--- a/install
+++ b/install
@@ -716,6 +716,13 @@ verbose "Using distribution id \"$dist\", release code \"$code\""
 # Detect init system type
 systemInitDetect
 
+# SysV is not supported, fail fast instead of cleaning the whole script
+# from sysv related entries.
+if $has_systemv_init; then
+    echo "ERROR: Installation on SysV init system is not supported!" >&2
+    exit 1
+fi
+
 if $is_centos_dist; then
   python_bin="python3.8"
   apache_bin="httpd"
@@ -1014,7 +1021,7 @@ loudCmd "$python_bin ${AIRTIMEROOT}/python_apps/api_clients/setup.py install --i
 verbose "...Done"
 
 verbose "\n * Installing pypo and liquidsoap..."
-loudCmd "$python_bin ${AIRTIMEROOT}/python_apps/pypo/setup.py install --install-scripts=/usr/bin --no-init-script"
+loudCmd "$python_bin ${AIRTIMEROOT}/python_apps/pypo/setup.py install --install-scripts=/usr/bin"
 loudCmd "mkdir -p /var/log/airtime/{pypo,pypo-liquidsoap} /var/tmp/airtime/pypo/{cache,files,tmp} /var/tmp/airtime/show-recorder/"
 loudCmd "chown -R ${web_user}:${web_user} /var/log/airtime/{pypo,pypo-liquidsoap} /var/tmp/airtime/pypo/{cache,files,tmp} /var/tmp/airtime/show-recorder/"
 systemInitInstall libretime-liquidsoap "$web_user"
@@ -1022,7 +1029,7 @@ systemInitInstall libretime-playout "$web_user"
 verbose "...Done"
 
 verbose "\n * Installing airtime-celery..."
-loudCmd "$python_bin ${AIRTIMEROOT}/python_apps/airtime-celery/setup.py install --no-init-script"
+loudCmd "$python_bin ${AIRTIMEROOT}/python_apps/airtime-celery/setup.py install"
 # Create the Celery user
 if $is_centos_dist; then
   loudCmd "id celery 2>/dev/null || adduser --no-create-home -c 'LibreTime Celery' -r celery || true"
