Fixed lxc-bootstrap to make a shallow clone, updated uninstall script, added initial debian wheezy requirements file

diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -1,16 +1,40 @@
 #!/bin/bash -e
-#-e Causes bash script to exit if any of the installers
-#return with a non-zero return value.
+# -e Causes bash script to exit if any of the steps
+# return with a non-zero return value.
 
 if [[ $EUID -ne 0 ]]; then
     echo "Please run as root user."
     exit 1
 fi
 
+getStorDirFromDatabase() {
+    # here-doc to execute this block as postgres user
+    su postgres <<'EOF'
+    set +e
+    result=$(psql -d airtime -tAc "SELECT directory FROM cc_music_dirs WHERE type='stor'")
+    set -e
+# don't indent this!
+EOF
+    echo $result
+}
+
+dropAirtimeDatabase() {
+    # here-doc to execute this block as postgres user
+    su postgres <<'EOF'
+    set +e
+    psql -d postgres -tAc "DROP DATABASE IF EXISTS airtime; DROP USER IF EXISTS airtime;"
+    set -e
+# don't indent this!
+EOF
+}
+
 SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
 AIRTIMEROOT=${SCRIPT_DIR}
 
+STOR_DIR=$(getStorDirFromDatabase)
+
 FILES=(
+     "${STOR_DIR}"
      "/etc/airtime"
      "/var/log/airtime"
      "/usr/lib/airtime"
@@ -27,11 +51,17 @@ for i in ${FILES[*]}; do
     echo $i
 done
 
-echo -e "\nThis will permanently remove Airtime and all related files from your computer. \
-Any files in Airtime directories will be deleted. Are you sure you want to proceed? (Y/n): \c"
+echo -e "\nThis will *permanently* remove Airtime and all related files from your computer. \
+Any files in Airtime directories and subdirectories will be deleted. Are you sure you want to proceed? (Y/n): \c"
 read IN
 if [[ ! ( "$IN" = "y" || "$IN" = "Y" ) ]]; then
     exit 0
+fi
+
+echo -e "\nAre you sure you want to remove your music storage directory ${STOR_DIR} and all of its subdirectories? (Y/n): \c"
+read IN
+if [[ "$IN" = "y" || "$IN" = "Y" ]]; then
+    rm -rf ${STOR_DIR}
 fi
 
 echo "Uninstalling Airtime..."
@@ -46,6 +76,8 @@ rm -f /usr/bin/airtime*
 
 rm -f /etc/apache2/sites-enabled/airtime*
 rm -f /etc/apache2/sites-available/airtime*
+
+dropAirtimeDatabase
 
 pip uninstall -y airtime-playout airtime-media-monitor
 echo "...Done"
