CC-3312: Upgrade scripts for 2.0.1
-Done

diff --git a/install_minimal/airtime-install b/install_minimal/airtime-install
--- a/install_minimal/airtime-install
+++ b/install_minimal/airtime-install
@@ -78,6 +78,31 @@ SCRIPT=`readlink -f $0`
 SCRIPTPATH=`dirname $SCRIPT`
 AIRTIMEROOT=$SCRIPTPATH/../
 
+#Check if required zend mvc and php-db libraries are present. This is a temporary workaround for 2.0.1, 
+#and we should probably create a seperate file that checks whether ALL dependencies are satisfied before 
+#allowing the install to continue. However in that case, we wouldn't check for Debian packages so that we 
+#can become less Debian platform dependent in the future...
+set +e
+dpkg -l | grep php-db > /dev/null 2>&1
+PHP_DB=$?
+
+dpkg -l | grep zendframework > /dev/null 2>&1
+ZENDFRAMEWORK=$?
+
+dpkg -l | grep libzend-framework-php > /dev/null 2>&1
+LIBZEND=$?
+set -e
+
+if [ "$PHP_DB" != "0" ]; then
+    echo "php-db package missing. Please run airtime-full-install"
+    exit 1
+fi
+
+if [ "$ZENDFRAMEWORK" != "0" -a "$LIBZEND" != "0" ]; then
+    echo "zendframework/libzend-framework-php package missing. Please run airtime-full-install"
+    exit 1
+fi
+
 # Check if airtime exists already
 set +e
 php --php-ini ${SCRIPTPATH}/airtime-php.ini ${SCRIPTPATH}/include/airtime-installed-check.php
