CC-2975: Require python-virtualenv version >= 1.4.9 for Airtime installations.
-fixed

diff --git a/install_minimal/airtime-install b/install_minimal/airtime-install
--- a/install_minimal/airtime-install
+++ b/install_minimal/airtime-install
@@ -15,6 +15,22 @@ if [[ "$DEB" = "Status: install ok installed" ]]; then
     exit 1
 fi
 
+
+#Check whether version of virtualenv is <= 1.4.5. If so exit install. 
+BAD_VERSION="1.4.8"
+VERSION=$(virtualenv --version)
+NEWEST_VERSION=$(echo -e "$BAD_VERSION\n$VERSION\n'" | sort -t '.' -g | tail -n 1)
+echo -n "Ensuring python-virtualenv version > $BAD_VERSION..."
+if [[ "$NEWEST_VERSION" = "$BAD_VERSION" ]]; then
+    URL="http://apt.sourcefabric.org/pool/main/p/python-virtualenv/python-virtualenv_1.4.9-3_all.deb"
+    echo "Failed!"
+    echo "You have version $BAD_VERSION or older installed. Please install package at $URL first and then try installing Airtime again."
+    exit 1
+else
+    echo "Success!"
+fi
+
+
 echo -e "\n******************************** Install Begin *********************************"
 
 # Absolute path to this script
