CC-3791: Media Monitor crash when there are media files with non-ascii name in watched folder
-move utf-8 locale check to bash

diff --git a/python_apps/media-monitor/airtime-media-monitor b/python_apps/media-monitor/airtime-media-monitor
--- a/python_apps/media-monitor/airtime-media-monitor
+++ b/python_apps/media-monitor/airtime-media-monitor
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -e
 
 # Location of pypo_cli.py Python script
 
@@ -13,6 +13,14 @@ api_client_path="/usr/lib/airtime/"
 cd ${media_monitor_path}
 
 exec 2>&1
+
+set +e
+cat /etc/default/locale | grep -i "LANG=.*UTF-\?8"
+set -e
+if [ "$?" != "0" ]; then
+    echo "non UTF-8 default locale found in /etc/default/locale." > /var/log/airtime/pypo/error.log
+    exit 1
+fi
 
 export PYTHONPATH=${api_client_path}
 export LC_ALL=`cat /etc/default/locale | grep "LANG=" | cut -d= -f2 | tr -d "\n\""`
diff --git a/python_apps/pypo/airtime-playout b/python_apps/pypo/airtime-playout
--- a/python_apps/pypo/airtime-playout
+++ b/python_apps/pypo/airtime-playout
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -e
 
 virtualenv_bin="/usr/lib/airtime/airtime_virtualenv/bin/"
 . ${virtualenv_bin}activate
@@ -11,6 +11,14 @@ api_client_path="/usr/lib/airtime/"
 pypo_script="pypocli.py"
 cd ${pypo_path}
 exec 2>&1
+
+set +e
+cat /etc/default/locale | grep -i "LANG=.*UTF-\?8"
+set -e
+if [ "$?" != "0" ]; then
+    echo "non UTF-8 default locale found in /etc/default/locale." > /var/log/airtime/pypo/error.log
+    exit 1
+fi
 
 export HOME="/var/tmp/airtime/pypo/"
 export PYTHONPATH=${api_client_path}:$PYTHONPATH
